-- =============================================================================
-- Migration: Transaction Deduplication
-- Description: Add transaction_id for preventing duplicate submissions
-- Date: 2025-01-10
-- =============================================================================

-- 1. Add transaction_id column to card_usage
ALTER TABLE card_usage 
ADD COLUMN IF NOT EXISTS transaction_id TEXT;

-- 2. Create unique index to prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS idx_card_usage_transaction_id 
ON card_usage(transaction_id) 
WHERE transaction_id IS NOT NULL;

-- 3. Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_card_usage_transaction_id_lookup 
ON card_usage(transaction_id);

-- 4. Add comment
COMMENT ON COLUMN card_usage.transaction_id IS 'Unique transaction ID generated by frontend to prevent duplicate submissions';
